# Generated by Django 4.2.7 on 2024-01-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_movielist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('GENRE_CHOICES', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
